spring:
  application:
    name: config-server
  profiles:
     active: native
  sleuth:
    sampler:
      probability: 0.1

# 调用github中的配置文件  
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/cheng6011/sp-config
#          searchPaths: config
#          #username: your-username
#          #password: your-password
 
 # 本地项目中resource中的config文件中        
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
          

          
  rabbitmq:
    host: 192.168.88.140
    port: 5672
    username: admin
    password: admin
    
server:
  port: 6001
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
